name       : pcre2
version    : 10.22
release    : 1
source     :
    - ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre2-10.22.tar.gz : 7627f93f2763ee6e11ac58558d8cfbf29e1070757b45571c0ba30ce9e096505c
license    : BSD-3-Clause
component  : programming.library
summary    : New PCRE library implementation
description: |
    PCRE2 is a re-working of the original PCRE library to provide an entirely new API.
builddeps  :
    - pkgconfig(valgrind)
patterns   :
    - devel:
        - /usr/bin
    - docs:
        - /usr/share/man
        - /usr/share/doc
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -v $installdir/usr/bin/pcre2{grep,test}
