name       : pcre2
version    : '10.42'
release    : 14
source     :
    - https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.42/pcre2-10.42.tar.bz2 : 8d36cd8cb6ea2a4c2bb358ff6411b0c788633a2a45dabbf1aeb4b701d1b5e840
homepage   : https://github.com/PCRE2Project/pcre2
license    : BSD-3-Clause
component  : system.base
emul32     : yes
summary    : PCRE2 - Perl-Compatible Regular Expressions
description: |
    The PCRE2 library is a set of C functions that implement regular expression pattern matching using the same syntax and semantics as Perl 5. PCRE2 has its own native API, as well as a set of wrapper functions that correspond to the POSIX regular expression API. The PCRE2 library is free, even for building proprietary software. It comes in three forms, for processing 8-bit, 16-bit, or 32-bit code units, in either literal or UTF encoding.
builddeps  :
    - pkgconfig(valgrind)
patterns   :
    - devel :
        - /usr/bin
        - /usr/share/man/man1/pcre2-config.1
    - docs :
        - /usr/share/doc
        - /usr/share/man/man3
setup      : |
    %configure --disable-static \
               --enable-pcre2-16 \
               --enable-pcre2-32 \
               --enable-jit
build      : |
    %make
install    : |
    %make_install
    rm -v $installdir/usr/bin/pcre2{grep,test}
    rm -v $installdir/usr/share/man/man1/pcre2{grep,test}.1
check      : |
    %make check
