name       : pcre2
version    : '10.34'
release    : 8
source     :
    - https://ftp.pcre.org/pub/pcre/pcre2-10.34.tar.gz : da6aba7ba2509e918e41f4f744a59fa41a2425c59a298a232e7fe85691e00379
license    : BSD-3-Clause
component  : programming.library
summary    : New PCRE library implementation
description: |
    PCRE2 is a re-working of the original PCRE library to provide an entirely new API.
builddeps  :
    - pkgconfig(valgrind)
patterns   :
    - devel :
        - /usr/bin
    - docs :
        - /usr/share/man
        - /usr/share/doc
setup      : |
    %configure --disable-static \
               --enable-pcre2-16 \
               --enable-pcre2-32 \
               --enable-jit
build      : |
    %make
install    : |
    %make_install
    rm -v $installdir/usr/bin/pcre2{grep,test}
check      : |
    %make check
