name       : pcre2
version    : '10.38'
release    : 9
source     :
    - https://github.com/PhilipHazel/pcre2/releases/download/pcre2-10.38/pcre2-10.38.tar.bz2 : 7d95aa7c8a7b0749bf03c4bd73626ab61dece7e3986b5a57f5ec39eebef6b07c
license    : BSD-3-Clause
component  : programming.library
summary    : New PCRE library implementation
description: |
    PCRE2 is a re-working of the original PCRE library to provide an entirely new API.
builddeps  :
    - pkgconfig(valgrind)
patterns   :
    - devel :
        - /usr/bin
    - docs :
        - /usr/share/man
        - /usr/share/doc
setup      : |
    %configure --disable-static \
               --enable-pcre2-16 \
               --enable-pcre2-32 \
               --enable-jit
build      : |
    %make
install    : |
    %make_install
    rm -v $installdir/usr/bin/pcre2{grep,test}
check      : |
    %make check
