name       : pcre2
version    : '10.30'
release    : 5
source     :
    - https://ftp.pcre.org/pub/pcre/pcre2-10.30.tar.bz2 : 90bd41c605d30e3745771eb81928d779f158081a51b2f314bbcc1f73de5773db
license    : BSD-3-Clause
component  : programming.library
summary    : New PCRE library implementation
description: |
    PCRE2 is a re-working of the original PCRE library to provide an entirely new API.
builddeps  :
    - pkgconfig(valgrind)
patterns   :
    - devel :
        - /usr/bin
    - docs :
        - /usr/share/man
        - /usr/share/doc
setup      : |
    #%patch -p2 < $pkgfiles/security/cve-2017-7186.patch
    #%patch -p2 < $pkgfiles/security/cve-2017-8786.patch
    %configure --disable-static \
               --enable-pcre2-16 \
               --enable-pcre2-32 \
               --enable-jit
build      : |
    %make
install    : |
    %make_install
    rm -v $installdir/usr/bin/pcre2{grep,test}
check      : |
    %make check
