name       : pcre2
version    : '10.40'
release    : 13
source     :
    - https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.40/pcre2-10.40.tar.bz2 : 14e4b83c4783933dc17e964318e6324f7cae1bc75d8f3c79bc6969f00c159d68
homepage   : https://github.com/PCRE2Project/pcre2
license    : BSD-3-Clause
component  : system.base
emul32     : yes
summary    : PCRE2 - Perl-Compatible Regular Expressions
description: |
    The PCRE2 library is a set of C functions that implement regular expression pattern matching using the same syntax and semantics as Perl 5. PCRE2 has its own native API, as well as a set of wrapper functions that correspond to the POSIX regular expression API. The PCRE2 library is free, even for building proprietary software. It comes in three forms, for processing 8-bit, 16-bit, or 32-bit code units, in either literal or UTF encoding.
builddeps  :
    - pkgconfig(valgrind)
patterns   :
    - devel :
        - /usr/bin
    - docs :
        - /usr/share/man
        - /usr/share/doc
setup      : |
    %configure --disable-static \
               --enable-pcre2-16 \
               --enable-pcre2-32 \
               --enable-jit
build      : |
    %make
install    : |
    %make_install
    rm -v $installdir/usr/bin/pcre2{grep,test}
check      : |
    %make check
